package com.example.competition.models.entity.enums;

public enum University {
    UNIVERSITY_OF_MADRAS,
    UNIVERSITY_OF_RUHUNA,
    UNIVERSITY_OF_PERADENIYA,
    AGRICULTURE_AND_FORESTRY_UNIVERSITY,
    POKHARA_UNIVERSITY,
    DR_BABASAHEB_AMBEDKAR_MARATHWADA_UNIVERSITY,
    RK_UNIVERSITY,
    IFUGAO_STATE_UNIVERSITY,
    BENGUET_STATE_UNIVERSITY,
    UNIVERSITY_OF_HYDERABAD,
    UNWE,
    UNIVERSITY_OF_THESSALY,
    VAMK,
    ECQ,
    ULSTER_UNIVERSITY
}
